require('nvim-treesitter.configs').setup({
    highlight = {
        enable = true,
        disable = {},
    },
    sync_install = true,
    ensure_installed = {
        "bash",
        "dockerfile",
        "go",
        "gomod",
        "vimdoc",
        "vim",
        "nix",
        "html",
        "json",
        "jsonnet",
        "terraform",
        "make",
        "markdown",
        "vue",
        "php",
        "puppet",
        "typescript",
        "javascript",
        "lua",
        "latex",
        "python",
        "regex",
        "ruby",
        "rust",
        "sql",
        "scss",
        "yaml",
    },
})

